In [44]:
data = {
    "Name" : ["abi", "achu", "abijith", None],
    "Age" : [1, 22, 27, 23],
    "salary" : ["$2100", 2000, "$2500,50", 500]
}

import pandas as pd

df = pd.DataFrame(data)

In [45]:
df

      Name  Age    salary
0      abi    1     $2100
1     achu   22      2000
2  abijith   27  $2500,50
3      NaN   23       500

In [46]:
df = df.dropna(subset=["Name"])

In [19]:
df

      Name  Age    salary
0      abi    1     $2100
1     achu   22      2000
2  abijith   27  $2500,50

In [47]:
df.loc[df["Age"] < 18,"Age"] = df["Age"].mean().astype(int)

In [22]:
df

      Name  Age    salary
0      abi   16     $2100
1     achu   22      2000
2  abijith   27  $2500,50

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   salary  3 non-null      object
dtypes: int64(1), object(1), str(1)
memory usage: 204.0+ bytes

In [56]:
df["salary"] = df["salary"].astype(str).str.replace(r'[^\d,]', "", regex=True)

In [58]:
df["salary"] = df["salary"].astype(str).str.replace(",",".", regex=False).astype(float).astype(int)

In [59]:
df

      Name  Age  salary
0      abi   16    2100
1     achu   22    2000
2  abijith   27    2500