In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df1 = pd.read_csv("/home/thinkpad/Documents/BrototypeStudying/Paper two/paper2/data/sales_dataset_467rows.csv")

In [6]:
df1.isnull().sum()

customer_id       0
customer_name     0
age              24
state             0
city              0
order_id          0
quantity          0
unit_price        0
salary           19
amount            0
dtype: int64

In [7]:
df1["age"].median()

np.float64(47.0)

In [8]:
df1["age"] = df1["age"].fillna(df1["age"].median())

In [9]:
df1["age"].isnull().sum()

np.int64(0)

In [10]:
df1[df1.duplicated()]

,customer_id,customer_name,age,state,city,order_id,quantity,unit_price,salary,amount
130,C1074,Saanvi Yadav,73.0,karnataka,Noida,O2173,10,3619.59,31730.95,36195.90
180,C1008,Ayaan Singh,62.0,West Bengal,Trivandrum,O2073,4,4623.36,80631.09,18493.44
206,C1035,Anika Joshi,21.0,TAMIL NADU,Trivandrum,O2009,3,3970.79,21670.41,11912.37
283,C1017,Amit Menon,33.0,Maharashtra,Jaipur,O2055,3,1230.80,27010.89,3692.40
289,C1010,Priya Das,33.0,tamil nadu,Mysuru,O2033,9,4426.47,80169.46,39838.23
294,C1061,Rahul Chatterjee,66.0,Maharashtra,Kolkata,O2063,8,2268.46,NaN,18147.68
338,C1098,Vivaan Iyer,67.0,MAHARASHTRA,Trivandrum,O2338,4,3404.59,57998.26,13618.36
364,C1005,Amit Gupta,66.0,Karnataka,Hyderabad,O2077,8,4584.56,76459.61,36676.48
366,C1020,Rohan Menon,42.0,PUNJAB,Kolkata,O2227,1,3201.90,23682.04,3201.90
385,C1069,Ishaan Shah,44.0,Maharashtra,Bengaluru,O2462,3,1483.50,79861.59,4450.50
444,C1058,Ayaan Mukherjee,35.0,Maharashtra,Mysuru,O2208,2,209.48,79566.94,418.96

In [11]:
df1 = df1.drop_duplicates()

In [12]:
df1.duplicated().sum()

np.int64(0)

In [13]:
df1["state"].unique()

<StringArray>
[  ' Telangana ',   'Karnataka  ',   ' Karnataka ',     'telangana',
  ' TAMIL NADU ',        'Kerala',     'karnataka',   ' RAJASTHAN ',
   'Telangana  ',      ' KERALA ',   ' KARNATAKA ',   'west bengal',
       ' DELHI ',     ' GUJARAT ', ' MAHARASHTRA ', ' Maharashtra ',
     'Gujarat  ',         'Delhi',  ' Tamil Nadu ',      ' PUNJAB ',
   'maharashtra',     'TELANGANA',       'Delhi  ', 'Maharashtra  ',
      ' Kerala ',     'Karnataka',   ' TELANGANA ',   'Maharashtra',
     'RAJASTHAN',        'Punjab',        'KERALA', 'West Bengal  ',
   ' Rajasthan ',     ' Gujarat ',         'DELHI',     'KARNATAKA',
    'tamil nadu',  'Tamil Nadu  ',    'Tamil Nadu',        'PUNJAB',
       ' Delhi ',      'Punjab  ',    'TAMIL NADU',       'GUJARAT',
      'Kerala  ',   'MAHARASHTRA',   'WEST BENGAL',     'Rajasthan',
        'punjab',         'delhi',      ' Punjab ',     'rajasthan',
       'Gujarat',   'West Bengal', ' West Bengal ',        'kerala',
       'gujarat', ' WEST BENGAL ',   'Rajasthan  ',     'Telangana']
Length: 60, dtype: str

In [14]:
state_map = {
    "KERALA" : "kerala"
}

In [15]:
df1["state"] = df1["state"].replace(state_map)

In [16]:
df1["state"].unique()

<StringArray>
[  ' Telangana ',   'Karnataka  ',   ' Karnataka ',     'telangana',
  ' TAMIL NADU ',        'Kerala',     'karnataka',   ' RAJASTHAN ',
   'Telangana  ',      ' KERALA ',   ' KARNATAKA ',   'west bengal',
       ' DELHI ',     ' GUJARAT ', ' MAHARASHTRA ', ' Maharashtra ',
     'Gujarat  ',         'Delhi',  ' Tamil Nadu ',      ' PUNJAB ',
   'maharashtra',     'TELANGANA',       'Delhi  ', 'Maharashtra  ',
      ' Kerala ',     'Karnataka',   ' TELANGANA ',   'Maharashtra',
     'RAJASTHAN',        'Punjab',        'kerala', 'West Bengal  ',
   ' Rajasthan ',     ' Gujarat ',         'DELHI',     'KARNATAKA',
    'tamil nadu',  'Tamil Nadu  ',    'Tamil Nadu',        'PUNJAB',
       ' Delhi ',      'Punjab  ',    'TAMIL NADU',       'GUJARAT',
      'Kerala  ',   'MAHARASHTRA',   'WEST BENGAL',     'Rajasthan',
        'punjab',         'delhi',      ' Punjab ',     'rajasthan',
       'Gujarat',   'West Bengal', ' West Bengal ',       'gujarat',
 ' WEST BENGAL ',   'Rajasthan  ',     'Telangana']
Length: 59, dtype: str

In [ ]:
df1["state"] = df1["state"].str.strip().

In [47]:
Q1 = df1["salary"].quantile(0.25)
Q3 = df1["salary"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier = df1[(df1["salary"] < lower_bound) | (df1["salary"] > upper_bound)]

print(outlier.shape[0])

7
95098.07250000001

In [19]:
# df1.loc[(df1["salary"] < lower_bound) | (df1["salary"] > upper_bound), "salary"] = df1["salary"].median()

In [20]:
df1["total_amount"] = df1["quantity"] * df1["unit_price"]

In [21]:
encoded = pd.get_dummies(data=df1, columns=["city"], drop_first=False, dtype=int)

In [22]:
print(encoded.head(5))

  customer_id  customer_name   age       state order_id  quantity  unit_price  \
0       C1036   Nikhil Gupta  32.0   telangana    O2293         6     2319.37
1       C1014    Ishaan Iyer  63.0   karnataka    O2283         3     2507.24
2       C1039      Divya Rao  69.0   karnataka    O2034         3     3695.99
3       C1105    Kavya Patel  62.0   telangana    O2380         9     3181.29
4       C1111  Aditya Pillai  41.0  tamil nadu    O2430         7     4656.89

      salary    amount  total_amount  ...  city_Hyderabad  city_Jaipur  \
0   75980.92  13916.22      13916.22  ...               0            0
1   69308.40   7521.72       7521.72  ...               0            0
2  112735.67  11087.97      11087.97  ...               0            0
3   80537.60  28631.61      28631.61  ...               0            0
4   83898.40  32598.23      32598.23  ...               0            0

   city_Kochi  city_Kolkata  city_Ludhiana  city_Mumbai  city_Mysuru  \
0           0             0              0            0            0
1           1             0              0            0            0
2           1             0              0            0            0
3           0             0              0            0            0
4           1             0              0            0            0

   city_Noida  city_Pune  city_Trivandrum
0           0          0                0
1           0          0                0
2           0          0                0
3           0          0                0
4           0          0                0

[5 rows x 25 columns]

In [23]:
customers = pd.read_csv("/home/thinkpad/Documents/BrototypeStudying/Paper two/paper2/data/customers.csv")
orders = pd.read_csv("/home/thinkpad/Documents/BrototypeStudying/Paper two/paper2/data/orders.csv")

In [24]:
print(customers.head(5),"\n\n\n" ,orders.head(5))

  customer_id customer_name       city         state
0       C1036  Vivaan Reddy    Kolkata   TAMIL NADU
1       C1014   Karan Reddy    Kolkata      Punjab
2       C1039  Ishaan Varma  Bengaluru      Kerala
3       C1105    Divya Shah  Hyderabad    tamil nadu
4       C1111    Pari Singh     Mumbai       Gujarat


   order_id customer_id  quantity  unit_price    amount
0    O2293       C1036         6     2319.37  13916.22
1    O2283       C1014         3     2507.24   7521.72
2    O2034       C1039         3     3695.99  11087.97
3    O2380       C1105         9     3181.29  28631.61
4    O2430       C1111         7     4656.89  32598.23

In [25]:
merged = customers.merge(orders, on="customer_id", how="left")

In [26]:
customersCopy = customers.copy()
customersCopy.drop(columns=["city"])

    customer_id    customer_name         state
0         C1036     Vivaan Reddy   TAMIL NADU
1         C1014      Karan Reddy      Punjab
2         C1039     Ishaan Varma      Kerala
3         C1105       Divya Shah    tamil nadu
4         C1111       Pari Singh       Gujarat
..          ...              ...           ...
147       C1153     Saanvi Patel    Karnataka
148       C1154       Navya Bose     karnataka
149       C1155      Riya Sharma     KARNATAKA
150       C1156       Amit Menon         delhi
151       C1157  Rahul Mukherjee     Karnataka

[152 rows x 3 columns]

In [27]:
print(orders.columns.tolist())

['order_id', 'customer_id', 'quantity', 'unit_price', 'amount']

In [28]:
merged = customers.merge(
    orders,
    on="customer_id",
    how="left"
)

In [29]:
# merged2 = customersCopy.merge(
#     orders,
#     on="customer_id",
#     how="left"
# )

In [30]:
merged.isna().head(5)

,customer_id,customer_name,city,state,order_id,quantity,unit_price,amount
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [31]:
print(customers["customer_id"].nunique())
print(orders["customer_id"].nunique())

152
144

In [32]:
orders.head(5)

  order_id customer_id  quantity  unit_price    amount
0    O2293       C1036         6     2319.37  13916.22
1    O2283       C1014         3     2507.24   7521.72
2    O2034       C1039         3     3695.99  11087.97
3    O2380       C1105         9     3181.29  28631.61
4    O2430       C1111         7     4656.89  32598.23

In [33]:
orders["customer_id"].unique()

<StringArray>
['C1036', 'C1014', 'C1039', 'C1105', 'C1111', 'C1109', 'C1037', 'C1047',
 'C1062', 'C1033',
 ...
 'C1096', 'C1138', 'C1048', 'C1007', 'C1147', 'C1114', 'C1127', 'C1046',
 'C1106', 'C1064']
Length: 144, dtype: str

In [34]:
customer_level = orders.groupby("customer_id").agg(
    total_spend = ("amount","sum"),
    orders_count = ("order_id","count")
).reset_index()

In [35]:
customer_level

    customer_id  total_spend  orders_count
0         C1000     54411.56             3
1         C1001     18166.96             3
2         C1002     44247.78             1
3         C1003      5938.78             2
4         C1004     36425.07             4
..          ...          ...           ...
139       C1145     96429.69             7
140       C1146     47188.19             3
141       C1147     82742.90             2
142       C1148     27443.95             2
143       C1149     91389.45             6

[144 rows x 3 columns]

In [36]:
customer_level.sort_values("total_spend", ascending=False).head(5)

    customer_id  total_spend  orders_count
72        C1074    151505.34             8
97        C1101    131528.88             6
10        C1010    123167.92             6
134       C1140    110013.52             7
120       C1126    109853.28             5

In [37]:
cust_order_merge = customers.merge(orders, on="customer_id")

In [38]:
print(customers.head(5), "\n\n\n\n", orders.head(5))

  customer_id customer_name       city         state
0       C1036  Vivaan Reddy    Kolkata   TAMIL NADU
1       C1014   Karan Reddy    Kolkata      Punjab
2       C1039  Ishaan Varma  Bengaluru      Kerala
3       C1105    Divya Shah  Hyderabad    tamil nadu
4       C1111    Pari Singh     Mumbai       Gujarat



   order_id customer_id  quantity  unit_price    amount
0    O2293       C1036         6     2319.37  13916.22
1    O2283       C1014         3     2507.24   7521.72
2    O2034       C1039         3     3695.99  11087.97
3    O2380       C1105         9     3181.29  28631.61
4    O2430       C1111         7     4656.89  32598.23

In [39]:
cust_order_merge.head(5)

,customer_id,customer_name,city,state,order_id,quantity,unit_price,amount
0,C1036,Vivaan Reddy,Kolkata,TAMIL NADU,O2293,6,2319.37,13916.22
1,C1036,Vivaan Reddy,Kolkata,TAMIL NADU,O2310,7,2950.78,20655.46
2,C1036,Vivaan Reddy,Kolkata,TAMIL NADU,O2314,2,4117.23,8234.46
3,C1014,Karan Reddy,Kolkata,Punjab,O2283,3,2507.24,7521.72
4,C1014,Karan Reddy,Kolkata,Punjab,O2343,8,4987.47,39899.76

In [40]:
top_cities = cust_order_merge.groupby("customer_id").agg(
    total_spend = ("amount","sum"),
    orders = ("order_id", "count")
).reset_index()
top_cities.sort_values("total_spend", ascending=False).head(5)

    customer_id  total_spend  orders
72        C1074    151505.34       8
97        C1101    131528.88       6
10        C1010    123167.92       6
134       C1140    110013.52       7
120       C1126    109853.28       5

In [41]:
top_cities = cust_order_merge.groupby(["city"]).agg(
    total_spend = ("amount","sum"),
    orders = ("order_id", "count")
).reset_index()
top_cities.sort_values("total_spend", ascending=False).head(5)

          city  total_spend  orders
10      Mumbai    692729.42      44
5    Hyderabad    634149.52      37
3   Coimbatore    553289.32      39
12       Noida    489149.83      40
0    Ahmedabad    458522.18      35

In [42]:
df1.head(5)

,customer_id,customer_name,age,state,city,order_id,quantity,unit_price,salary,amount,total_amount
0,C1036,Nikhil Gupta,32.0,telangana,Coimbatore,O2293,6,2319.37,75980.92,13916.22,13916.22
1,C1014,Ishaan Iyer,63.0,karnataka,Kochi,O2283,3,2507.24,69308.40,7521.72,7521.72
2,C1039,Divya Rao,69.0,karnataka,Kochi,O2034,3,3695.99,112735.67,11087.97,11087.97
3,C1105,Kavya Patel,62.0,telangana,Coimbatore,O2380,9,3181.29,80537.60,28631.61,28631.61
4,C1111,Aditya Pillai,41.0,tamil nadu,Kochi,O2430,7,4656.89,83898.40,32598.23,32598.23

In [43]:
data = {
    "name" : ["Abi", "Achu", "Abijith", "Ara"],
    "age" : [20,21,22,None]
}

df = pd.DataFrame(data)

In [44]:
df2 = pd.read_csv("/home/thinkpad/Documents/BrototypeStudying/Paper two/paper2/data/employees_practice.csv")

In [45]:
def preprossing(df : pd.DataFrame):
    
    numeric_col = df.select_dtypes(include="number").columns.tolist()
    category_col = df.select_dtypes(include=["object", "str"]).columns.tolist()
    
    null_in_number = df[numeric_col].isnull().sum()
    print("number colums\n\n\n", null_in_number)
    df[numeric_col] = df[numeric_col].fillna(df[numeric_col].median())
    
    print(df[numeric_col])
    
    return df , category_col

In [46]:
preprossing(df2)

number colums


 employee_id         0
age                 3
experience_years    2
salary              2
dtype: int64
   employee_id   age  experience_years   salary
0          101  29.0               4.0  42000.0
1          102  35.0               9.0  58000.0
2          103  41.0               5.5  49500.0
3          104  35.0               6.0  51000.0
4          105  35.0               3.0  39000.0
5          106  38.0               5.5  62000.0
6          107  27.0               2.0  49500.0
7          108  45.0              15.0  71000.0
8          109  35.0               5.0  45500.0
9          110  33.0               7.0  48000.0

(   employee_id          name department   age  experience_years   salary  \
 0          101      Anu Nair     sales   29.0               4.0  42000.0
 1          102   Rahul Menon         IT  35.0               9.0  58000.0
 2          103     Priya Das         HR  41.0               5.5  49500.0
 3          104    Arjun Iyer      sales  35.0               6.0  51000.0
 4          105  Meera Pillai        IT   35.0               3.0  39000.0
 5          106  Vishnu Kumar    Finance  38.0               5.5  62000.0
 6          107   Divya Varma         hr  27.0               2.0  49500.0
 7          108  Kiran Thomas         IT  45.0              15.0  71000.0
 8          109    Sneha Jose    FINANCE  35.0               5.0  45500.0
 9          110     Rohit Raj      Sales  33.0               7.0  48000.0

       rating
 0       Good
 1  Excellent
 2    Average
 3        NaN
 4       Good
 5  Excellent
 6    Average
 7        NaN
 8       Good
 9  Excellent  ,
 ['name', 'department', 'rating'])