In [10]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110,
                    111,112,113,114,115,116,117,118,119,120],

    "Age": [23,25,31,29,40,35,28,26,45,38,
            32,np.nan,27,30,50,41,24,33,36,29],

    "Gender": [
        "Male","Female","male","Female","Male",
        "Female","Male","female","Male","Female",
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female"
    ],

    "City": [
        "Kochi","Calicut","Kochi","Kannur","Calicut",
        "Kochi","Kannur","Calicut","Kochi","Kannur",
        "Kochi","Calicut","Kannur","Kochi","Calicut",
        "Kannur","Kochi","Calicut","Kannur","Kochi"
    ],

    "Product": [
        "Laptop","Phone","Phone","Laptop","Tablet",
        "Phone","Laptop","Tablet","Phone","Laptop",
        "Tablet","Phone","Laptop","Tablet","Phone",
        "Laptop","Phone","Tablet","Laptop","Phone"
    ],

    "Quantity": [
        1,2,1,1,3,
        2,1,2,4,1,
        2,3,1,2,2,
        1,3,2,1,4
    ],

    "Price": [
        55000,25000,24000,60000,18000,
        26000,58000,17000,22000,62000,
        19000,23000,57000,18500,25500,
        61000,24500,17500,59000,23500
    ],

    "Rating": [
        4.5,4.0,3.8,4.7,3.5,
        4.1,4.6,np.nan,3.9,4.8,
        3.6,4.0,4.4,3.7,4.2,
        4.9,3.8,3.5,4.6,4.1
    ],

    "Discount": [
        5,10,0,8,15,
        5,7,12,10,6,
        15,5,8,10,5,
        7,10,12,6,5
    ]
}

df = pd.DataFrame(data)

In [11]:
df.head(3)

,Customer_ID,Age,Gender,City,Product,Quantity,Price,Rating,Discount
0,101,23.0,Male,Kochi,Laptop,1,55000,4.5,5
1,102,25.0,Female,Calicut,Phone,2,25000,4.0,10
2,103,31.0,male,Kochi,Phone,1,24000,3.8,0

In [12]:
df.tail(3)

,Customer_ID,Age,Gender,City,Product,Quantity,Price,Rating,Discount
17,118,33.0,Female,Calicut,Tablet,2,17500,3.5,12
18,119,36.0,Male,Kannur,Laptop,1,59000,4.6,6
19,120,29.0,Female,Kochi,Phone,4,23500,4.1,5

In [13]:
df.shape

(20, 9)

In [14]:
df.isnull().sum()

Customer_ID    0
Age            1
Gender         0
City           0
Product        0
Quantity       0
Price          0
Rating         1
Discount       0
dtype: int64

In [15]:
df["Age"].mean()

np.float64(32.73684210526316)

In [16]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [17]:
df["Rating"] = df["Rating"].fillna(df["Rating"].median())

In [18]:
df.isnull().sum()

Customer_ID    0
Age            0
Gender         0
City           0
Product        0
Quantity       0
Price          0
Rating         0
Discount       0
dtype: int64

In [19]:
df["Gender"]

0       Male
1     Female
2       male
3     Female
4       Male
5     Female
6       Male
7     female
8       Male
9     Female
10      Male
11    Female
12      Male
13    Female
14      Male
15    Female
16      Male
17    Female
18      Male
19    Female
Name: Gender, dtype: str

In [20]:
df["Gender"].value_counts()

Gender
Male      9
Female    9
male      1
female    1
Name: count, dtype: int64

In [21]:
df["Gender"] = df["Gender"].str.strip().str.lower()

In [22]:
df["Gender"]

0       male
1     female
2       male
3     female
4       male
5     female
6       male
7     female
8       male
9     female
10      male
11    female
12      male
13    female
14      male
15    female
16      male
17    female
18      male
19    female
Name: Gender, dtype: str

In [23]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Product', 'Quantity', 'Price',
       'Rating', 'Discount'],
      dtype='str')

In [24]:
df.head(3)

,Customer_ID,Age,Gender,City,Product,Quantity,Price,Rating,Discount
0,101,23.0,male,Kochi,Laptop,1,55000,4.5,5
1,102,25.0,female,Calicut,Phone,2,25000,4.0,10
2,103,31.0,male,Kochi,Phone,1,24000,3.8,0

In [25]:
df["Total"] = df["Quantity"] * df["Price"]

In [26]:
df.groupby("Product")["Total"].agg("sum")

Product
Laptop    412000
Phone     501500
Tablet    198000
Name: Total, dtype: int64

In [27]:
df.groupby("Product")["Rating"].agg("mean")

Product
Laptop    4.642857
Phone     3.987500
Tablet    3.680000
Name: Rating, dtype: float64

In [28]:
#number of cust from each city

In [29]:
df.groupby("City")["Customer_ID"].agg("count")

City
Calicut    6
Kannur     6
Kochi      8
Name: Customer_ID, dtype: int64